name: CI
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - uses: manyuanrong/setup-ossutil@v2.0
        with:
          # endpoint 可以去oss控制台上查看
          endpoint: "oss-cn-beijing.aliyuncs.com"
          # 使用我们之前配置在secrets里面的accesskeys来配置ossutil
          access-key-id: ${{ secrets.OSS_ACCESS_KEY_ID }}
          access-key-secret: ${{ secrets.OSS_ACCESS_KEY_SECRET }}

      # TODO(ZhaoYingkai)
      - name: SetUp UITest Environment
        run: |
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo dpkg -i google-chrome-stable_current_amd64.deb
          sudo apt-get install xvfb
          sudo wget http://chromedriver.storage.googleapis.com/79.0.3945.88/chromedriver_linux64.zip
          sudo apt-get install unzip -y
          unzip chromedriver_linux64.zip
          sudo mv -f chromedriver /usr/local/share/chromedriver
          sudo ln -s /usr/local/share/chromedriver /usr/local/bin/chromedriver
          sudo ln -s /usr/local/share/chromedriver /usr/bin/chromedriver
          chromedriver --version
          sudo apt-get install python3 -y
          pip3 install selenium
      
      - name: Run UITest
        run: python3 ./src/test/runner.py

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.3.0

      - name: run npm build
        run: |
          npm install
          npm run build

      - name: Deply To OSS
        run: |
          ossutil rm -r -f oss://cqu-teapot/wespace/
          ossutil cp -r -f dist oss://cqu-teapot/wespace/
