name: CI
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - uses: manyuanrong/setup-ossutil@v2.0
        with:
          # endpoint 可以去oss控制台上查看
          endpoint: "oss-cn-beijing.aliyuncs.com"
          # 使用我们之前配置在secrets里面的accesskeys来配置ossutil
          access-key-id: ${{ secrets.OSS_ACCESS_KEY_ID }}
          access-key-secret: ${{ secrets.OSS_ACCESS_KEY_SECRET }}

      - name: Setup Chrome
        run: |
          sudo sh -c 'echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
          sudo apt-get update -y
          sudo apt-get install google-chrome -y
            
      # TODO(ZhaoYingkai=
      - uses: nanasess/setup-chromedriver@master
      
      - name: Setup Python
        uses: actions/setup-python@v2.2.2

      - name: SetUp Python
        run: |
          pip3 install selenium
      
      - name: Run UITest
        run: python3 ./src/test/runner.py

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.3.0

      - name: run npm build
        run: |
          npm install
          npm run build

      - name: Deply To OSS
        run: |
          ossutil rm -r -f oss://cqu-teapot/wespace/
          ossutil cp -r -f dist oss://cqu-teapot/wespace/
